# Generated by Django 5.2.13 on 2026-04-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MinimalPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_1', models.CharField(max_length=10)),
                ('sound_2', models.CharField(max_length=10)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minimal_pairs', to='content.language')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('sound', models.CharField(max_length=10)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('minimal_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='content.minimalpair')),
            ],
        ),
    ]
