# Generated by Django 5.2.13 on 2026-04-08 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_alter_word_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('duration_chosen', models.IntegerField()),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('minimal_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='content.minimalpair')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
